server:
  port: 8080
spring:
  application:
    name: cassandra-testcontainer
  autoconfigure.exclude: org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration

cassandra:
  contactpoints: localhost
  port: 9042
  keyspace: myspace
